# docker compose -f docker-compose.yml up
version: '3.7'
services:
  backend_app:
    container_name: app20222_backend
    image: app20222_backend:1.0.0
    build:
      dockerfile: Dockerfile
      context: app20222_backend
    ports:
      - '8082:8082'
